vsphere_server = "irvc01.iroo.int"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "Vmware!0"
datacenter = "DC-MGMT"
cluster = "MGMT-CLUST"
datastore = "IRNAS4-NFS"
network_name = "net-int"
